
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkgvjfxiyaqqbniasppz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprZ3ZqZnhpeWFxcWJuaWFzcHB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MDA2MjQsImV4cCI6MjA1OTE3NjYyNH0.adxmGOHysvDyQ9hxYVqPIZySHuIviue7E9Ud_h38PdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
